add enemy detection function
karamarimo/HachitaiGame pull request #8
Opened 2016-09-30 09:45 UTC by karamarimo

this function checks whether an enemy sees the player considering
obstacles

2016-10-01 12:09 UTC, kameike requested changes
レビュー遅くなってごめんねえ

2016-10-01 12:09 UTC, kameike commented on HachitaiGame.xcodeproj/project.pbxproj
> -<?xml version="1.0" encoding="UTF-8"?>
Xcode Project のマージはマージツールを使うといいよ
　https://github.com/simonwagner/mergepbx

2016-10-01 12:09 UTC, kameike commented on HachitaiGame/EnemyController.swift
> +    public var enemies: [EnemyNode] = []
enemy contorllerが enemyのことを知りすぎてるのが結構問題
enemyとplayerを密結合にしてしまっている

MVCモデルのcontrollerの意味なら 実質ViewはSKSpriteNodeになるのでEnemyに実装したほうがいいと思う

2016-10-01 12:09 UTC, kameike commented on HachitaiGame/EnemyController.swift
> +        let vec = CGPointSubtract(player!.position, enemy.position)
これはEnemy内に detect(target: SKSpriteNode)で個別に実装するといいと思う。

2016-10-01 12:09 UTC, kameike commented on HachitaiGame/EnemyController.swift
> +                enemy.color = UIColor.purple
ここでdetect(target: SKSpriteNode) にplayerを渡してあげる。


そうするとこのクラスの役目はviewのアップデートだからどちらかというとマネージャークラスだね。
detect(target: SKSpriteNode)は今のようにBoolを返せば処理できるはず。

ただし見つかった場合UI等いろんなところでイベントを処理することがあるから
detect(target: SKSpriteNode)はVoidを返すようにして
PUBSUBモデルを取り入れるとより疎結合を保つことができる
https://www.pubnub.com/ を使ったりしよう
podからインストールできる。

クラスのリネームもしてしまおう

2016-10-01 12:09 UTC, kameike commented on HachitaiGame.xcodeproj/project.pbxproj
> -<?xml version="1.0" encoding="UTF-8"?>
これは次回からだね

2016-10-02 07:49 UTC, karamarimo commented
pubnubってネット越しに通信するみたいですが、ゲームシステムにも使えるんですか？pubnubのネットワークを介さずに通信できるんでしょうか？

2016-10-04 00:13 UTC, kameike commented
ごめん　https://github.com/cesarferreira/SwiftEventBus　こっちだった（土下座）

2016-10-04 04:43 UTC, karamarimo commented on HachitaiGame/Enemy.swift
> +        patrolAnimation = SKAction.repeatForever(SKAction.sequence([
敵が歩き回るようになりました。

2016-10-06 02:15 UTC, kameike commented on HachitaiGame/Enemy.swift
> +        patrolAnimation = SKAction.repeatForever(SKAction.sequence([
:)

2016-10-06 15:04 UTC, kameike requested changes
コードレビューしたよ。いいねじっこうしたら楽しい

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
> +        patrolAnimation = SKAction.repeatForever(SKAction.sequence([
ここの部分関数に分けたほうがいいかもね
private func attchAnimation みたいな

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
> +        let detectingPlayer = { () -> Bool in
ここなんでlambdaにしているの？

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
> +            self.scene?.physicsWorld.enumerateBodies(alongRayStart: self.position, end: target.position, using: { (body: SKPhysicsBody, point: CGPoint, normal: CGVector, stop: UnsafeMutablePointer<Ob
現在走査線を一本しか出していないみたいだけど、敵の視野の実装どうする感じなの？
イメージはどんな感じ？

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
>          fovPath.move(to: CGPoint(x: 0, y: 0))
ここも  pathを書くfunctionに分けたほうがいいかもね。

多分枚フレームごとに描画し直す感じじゃないのかな？

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
>          fovPath.move(to: CGPoint(x: 0, y: 0))
ということで毎フレーム障害物に遮られる視野を描かないとね。

障害物の移動の後だから、magenerからのeventをListenしてmanger.getAllObstacleみたいな実装がよいのではないでしょうか？

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
> +    var patrolAnimation: SKAction!
変数はprivateにしよう

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
> +    public func detect(target: SKSpriteNode) {
ここのスコープはinternalが良いのではないでしょうか？

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/Enemy.swift
> +            self.scene?.physicsWorld.enumerateBodies(alongRayStart: self.position, end: target.position, using: { (body: SKPhysicsBody, point: CGPoint, normal: CGVector, stop: UnsafeMutablePointer<Ob
あとあとここ　enumerateBodiesの関数が長いから適当に改行で切り分けたほうがいいかもね

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/EnemyManager.swift
> +            enemy.detect(target: player!)
ちなみにここせっかくだからeventBusで実装してもいいかもね。

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/GameScene.swift
> +            self.restartScene()
i see you がハードコーディングになっているから、どっかにclassをつくってletなプロパティにしようか

2016-10-06 15:04 UTC, kameike commented on HachitaiGame/GameScene.swift
> +            self.restartScene()
Game.Enemy.findTarget 見たいにかけるといいかもね。

2016-10-06 23:48 UTC, karamarimo commented on HachitaiGame/Enemy.swift
> +    public func detect(target: SKSpriteNode) {
あ、internalの存在を知りませんでした。そうですね。

2016-10-06 23:51 UTC, karamarimo commented on HachitaiGame/Enemy.swift
> +        let detectingPlayer = { () -> Bool in
if を３重にするより見栄えがいいかなと思ったので...functionを別に作ったほうがいいですか？

2016-10-07 00:02 UTC, kameike commented on HachitaiGame/Enemy.swift
> +        let detectingPlayer = { () -> Bool in
いや、そのままλとっちゃって
unobstructed そのまま使えばよくない？

2016-10-07 03:19 UTC, karamarimo commented on HachitaiGame/Enemy.swift
> +        let detectingPlayer = { () -> Bool in
あっそうですね。
targetが見えなかったら何も処理しなくていいってことを見落としてました。

2016-10-07 03:27 UTC, karamarimo commented on HachitaiGame/Enemy.swift
> +            self.scene?.physicsWorld.enumerateBodies(alongRayStart: self.position, end: target.position, using: { (body: SKPhysicsBody, point: CGPoint, normal: CGVector, stop: UnsafeMutablePointer<Ob
敵の視野は、楽な方法を模索中です。lightnodeを使って表現するっていうのを考えましたが、lightnodeは全方位にしか光が出せないし、影の表現がチープ(光が障害物をはみ出す)なんで諦めました。
地道に計算するしかないんでしょうかね。

2016-10-07 13:42 UTC, karamarimo commented on HachitaiGame/EnemyManager.swift
> +            enemy.detect(target: player!)
EnemyManagerがpublish、EnemyがsubscribeしてEnemyにdetectさせるってことですか？

2016-10-07 23:34 UTC, kameike commented on HachitaiGame/Enemy.swift
> +            self.scene?.physicsWorld.enumerateBodies(alongRayStart: self.position, end: target.position, using: { (body: SKPhysicsBody, point: CGPoint, normal: CGVector, stop: UnsafeMutablePointer<Ob
多分地道にするしかないのではー

2016-10-08 08:42 UTC, karamarimo commented
scene が切り替わってもなぜか enemy node がメモリから消えません...。
参照のグラフ
![メモリグラフ](http://imgur.com/oBbmVSn.png)

2016-10-10 11:12 UTC, kameike commented
ちゃんとマネージャーとかは消えてるんだよね？

2016-10-10 14:01 UTC, karamarimo commented
あとなぜかPlayerControllerNodeが最初から2つメモリにあります。ゲームオーバーを繰り返しても増えません。
GameScene、PlayerNode、EnemyManagerとかはちゃんと消えます。

2016-10-10 16:11 UTC, kameike commented on HachitaiGame/EnemyManager.swift
> +            enemy.detect(target: player!)
そうそう。

2016-10-10 17:07 UTC, kameike requested changes
でばっかで止めて見たらGameSceneじたい二回つくられてるね。原因は不明（おそらくStartScene viewloadedでシーンを切り替えちゃってるから）

でもPlayerControllerがリークしてるのは謎。ちなみにSKButtonめっちゃリークしてる笑

ラムダでキャプチャしちゃってるからねぇ

2016-10-10 17:07 UTC, kameike commented on HachitaiGame/Enemy.swift
> +            SwiftEventBus.post(GameConst.Enemy.playerFound, sender: self)
ここでEnemy.removeAllActionしたらメモリリークなるなるはず

2016-10-10 17:07 UTC, kameike commented on HachitaiGame/GameConst.swift
> +        static let playerFound = "player found"
これイベントの名前だから[Enemy.foundPlayer]的な文にしたほうがいいと思う。

2016-10-10 17:07 UTC, kameike commented on HachitaiGame/Enemy.swift
> +            SwiftEventBus.unregister(self)
ここちゃんとunregisterしてて良いと思います。素晴らしい〜〜

2016-10-10 17:11 UTC, kameike commented on HachitaiGame/GameConst.swift
> +        static let playerFound = "player found"
イベントは現在形がよいんだっけ、ちょっと調べて見てくだされ〜

2016-10-14 12:19 UTC, karamarimo commented on HachitaiGame/Enemy.swift
> +            SwiftEventBus.post(GameConst.Enemy.playerFound, sender: self)
gameSceneFinishedイベントのとこでもいいですか？

2016-10-18 09:13 UTC, karamarimo commented
やっと視野の表示できました。
なかなか難しかったです。

2016-10-19 11:30 UTC, karamarimo commented
メモリリーク直りました。

2016-10-30 15:07 UTC, karamarimo commented
マージしてよろしいでしょうか

2016-10-31 14:54 UTC, kameike approved these changes

2016-10-31 14:54 UTC, kameike commented
反応遅うなってごめんねーいいのでは

2016-10-31 15:24 UTC, merged